### ISSUE TITLE
Add some shadow or border for context menu

### ISSUE THREAD

**Issue by bykka** [mkpaz/atlantafx#12]
A "context menu" component does not have any shadow and especially in the case of "table view" it's difficult to distinguish where is data and where is a context menu.

![image](https://user-images.githubusercontent.com/489997/190171818-b69ead2a-5e8e-4b57-a3a9-8bae5ef2fc95.png)
![image](https://user-images.githubusercontent.com/489997/190171860-674170c4-7a67-4921-9db2-5adfb8ef366d.png)

**Comment by mkpaz** [comment]
Yes, this doesn't look good, thanks for pointing out. There's a shadow, but it uses wrong color. I should revisit this aspect. As well  as tooltips and popovers.

**Comment by mkpaz** [comment]
You can try this as temp fix.

```css
.context-menu {
  -fx-effect: dropshadow(three-pass-box, -color-border-muted, 6, 0.5, 0, 1);
}

.root:dark {
  .context-menu {
    -fx-effect: dropshadow(three-pass-box, -color-bg-inset, 8, 0.5, 0, 2);
  }
}
```
