### ISSUE TITLE
RadioButton Background Color

### ISSUE THREAD

**Issue by robbiezl** [mkpaz/atlantafx#60]
I found radio-button has a backgournd color,I think it should have no background,it should be transparent

.radio-button {
  -fx-background-color: -color-bg-default;
  -fx-text-fill: -color-fg-default;
  -fx-label-padding: 2px 2px 0 6px;
}

**Comment by mkpaz** [comment]
No, it can't be transparent, because radio button uses bg insets to draw its borders. So, it's basically the white circle above the gray circle, you can't make the top layer transparent. It would be possible if it used the border stroke instead of bg insets.

**Comment by robbiezl** [comment]
I found some component's padding size is different compare with the modena.css,this may cause incomplete text display.
for example, in modena css button's padding:

-fx-padding: 0.333333em 0.666667em 0.333333em 0.666667em; /* 4 8 4 8 */

in cupertino-light button's padding:

-fx-padding: 6px 12px 6px 12px;****

**Comment by dlemmermann** [comment]
@mkpaz in which theme does the `RadioButton` draw borders? In _nord-light.css_ I can see this:

```css
.radio-button {
  -fx-background-color: -color-bg-default;
  -fx-text-fill: -color-fg-default;
  -fx-label-padding: 2px 2px 0 6px;
}
```

It is only the ".radio" rule that defines insets:

```css
.radio-button > .radio {
  -fx-background-color: -color-border-default, -color-bg-default;
  -fx-background-insets: 0, 1.5px;
  -fx-background-radius: 1em;
  -fx-padding: 3px;
  -fx-alignment: CENTER;
}
```

I currently have to explicitly override the radio buttons background color to "transparent" whenever I use it on something that does not have `-color-bg-default` as their background color. The following screenshot shows the issue when I do not do that.

<img width="210" height="49" alt="Image" src="https://github.com/user-attachments/assets/d042ae52-d2a8-4601-a0d0-00b9ce5daaa9" />
