### ISSUE TITLE
Scrollbar bleeding with ModalPane

### ISSUE THREAD

**Issue by mcantrell** [mkpaz/atlantafx#88]
The opacity settings for the scrollbars can cause some unwanted bleeding in the modal panels.

<img width="1392" alt="image" src="https://github.com/mkpaz/atlantafx/assets/20870/fa59d06b-2201-4455-b6e9-af871f711f17">

Potential fix:

```css
.modal-pane .scroll-bar {
    -fx-opacity: 1.0;
}
```
